import { useState } from 'react';
import { uid } from '../lib/storage';

interface HandoverItem {
  id: string;
  house: string;
  category: 'incident' | 'medication' | 'client_update' | 'task' | 'general';
  text: string;
  severity: 'red' | 'amber' | 'none';
  resolved: boolean;
}

interface Handover {
  id: string;
  date: string;
  shiftFrom: string;
  shiftTo: string;
  house: string;
  staffOut: string;
  staffIn: string;
  items: HandoverItem[];
  createdAt: string;
}

const HOUSES = [
  'Lingfield House', 'Church House', 'Laurel House', 'Station House',
  'Canterbury', 'Glenfrome House', 'Woburn House', 'Hazelbury House',
  'Courtney Lodge', 'Cottrell House',
];

const CATEGORIES: { id: HandoverItem['category']; label: string; color: string; icon: string }[] = [
  { id: 'incident', label: 'Incident', color: '#ef4444', icon: 'M12 9v2m0 4h.01' },
  { id: 'medication', label: 'Medication', color: '#14b8a6', icon: 'M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z' },
  { id: 'client_update', label: 'Client Update', color: '#3b82f6', icon: 'M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0' },
  { id: 'task', label: 'Outstanding Task', color: '#f59e0b', icon: 'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z' },
  { id: 'general', label: 'General', color: '#64748b', icon: 'M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z' },
];

const STORAGE_KEY = 'hazelcare-handovers';

function loadHandovers(): Handover[] {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { return []; }
}

function saveHandovers(h: Handover[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(h));
}

export function HandoverPage() {
  const [house, setHouse] = useState(HOUSES[0]);
  const [shiftFrom, setShiftFrom] = useState('Day');
  const [shiftTo, setShiftTo] = useState('Night');
  const [staffOut, setStaffOut] = useState('');
  const [staffIn, setStaffIn] = useState('');
  const [items, setItems] = useState<HandoverItem[]>([]);
  const [newText, setNewText] = useState('');
  const [newCategory, setNewCategory] = useState<HandoverItem['category']>('general');
  const [newSeverity, setNewSeverity] = useState<'red' | 'amber' | 'none'>('none');
  const [history, setHistory] = useState<Handover[]>(loadHandovers);
  const [showHistory, setShowHistory] = useState(false);
  const [copied, setCopied] = useState(false);

  function addItem() {
    if (!newText.trim()) return;
    setItems([...items, {
      id: uid(),
      house,
      category: newCategory,
      text: newText.trim(),
      severity: newSeverity,
      resolved: false,
    }]);
    setNewText('');
    setNewSeverity('none');
  }

  function removeItem(id: string) {
    setItems(items.filter(i => i.id !== id));
  }

  function toggleResolved(id: string) {
    setItems(items.map(i => i.id === id ? { ...i, resolved: !i.resolved } : i));
  }

  function generateHandoverText(): string {
    const now = new Date();
    let text = `SHIFT HANDOVER — ${house}\n`;
    text += `Date: ${now.toLocaleDateString('en-GB')}\n`;
    text += `Shift: ${shiftFrom} → ${shiftTo}\n`;
    text += `Outgoing: ${staffOut || '___'} | Incoming: ${staffIn || '___'}\n`;
    text += `${'─'.repeat(50)}\n\n`;

    const grouped: Record<string, HandoverItem[]> = {};
    for (const item of items) {
      (grouped[item.category] ??= []).push(item);
    }

    for (const cat of CATEGORIES) {
      const catItems = grouped[cat.id];
      if (!catItems?.length) continue;
      text += `${cat.label.toUpperCase()}\n`;
      for (const item of catItems) {
        const flag = item.severity === 'red' ? ' [RED FLAG]' : item.severity === 'amber' ? ' [AMBER]' : '';
        const status = item.resolved ? ' ✓ Resolved' : '';
        text += `  • ${item.text}${flag}${status}\n`;
      }
      text += '\n';
    }

    const unresolved = items.filter(i => !i.resolved);
    if (unresolved.length > 0) {
      text += `CARRY FORWARD (${unresolved.length} items)\n`;
      for (const item of unresolved) {
        text += `  → ${item.text}\n`;
      }
      text += '\n';
    }

    text += `${'─'.repeat(50)}\n`;
    text += `Generated by Hazelcare Ops Engine · ${now.toLocaleDateString('en-GB')} ${now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
    return text;
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(generateHandoverText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function saveHandover() {
    const handover: Handover = {
      id: uid(),
      date: new Date().toLocaleDateString('en-GB'),
      shiftFrom, shiftTo, house, staffOut, staffIn,
      items: [...items],
      createdAt: new Date().toISOString(),
    };
    const updated = [handover, ...history].slice(0, 50);
    setHistory(updated);
    saveHandovers(updated);
    setItems([]);
    setStaffOut('');
    setStaffIn('');
  }

  return (
    <div className="p-6 lg:p-8 max-w-[1400px] mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-white mb-1">Shift Handover</h1>
        <p className="text-hc-muted text-sm">Build a structured handover that carries forward unresolved items automatically.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Left — Input */}
        <div className="lg:col-span-3 space-y-4">
          {/* Meta */}
          <div className="bg-hc-card border border-hc-border rounded-xl p-4">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
              <div>
                <label className="text-[10px] text-hc-muted uppercase tracking-wider font-semibold mb-1 block">House</label>
                <select value={house} onChange={e => setHouse(e.target.value)} className="w-full bg-hc-dark border border-hc-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-hc-teal-light">
                  {HOUSES.map(h => <option key={h} value={h}>{h}</option>)}
                </select>
              </div>
              <div>
                <label className="text-[10px] text-hc-muted uppercase tracking-wider font-semibold mb-1 block">Shift</label>
                <div className="flex gap-1">
                  {['Day → Night', 'Night → Day'].map(s => {
                    const [from, to] = s.split(' → ');
                    const active = shiftFrom === from;
                    return (
                      <button key={s} onClick={() => { setShiftFrom(from); setShiftTo(to); }} className={`flex-1 text-xs py-2 rounded-lg border transition-all ${active ? 'bg-hc-teal/15 border-hc-teal/30 text-hc-teal-light' : 'border-hc-border text-hc-muted hover:text-white'}`}>
                        {s}
                      </button>
                    );
                  })}
                </div>
              </div>
              <div>
                <label className="text-[10px] text-hc-muted uppercase tracking-wider font-semibold mb-1 block">Outgoing Staff</label>
                <input value={staffOut} onChange={e => setStaffOut(e.target.value)} placeholder="Name" className="w-full bg-hc-dark border border-hc-border rounded-lg px-3 py-2 text-sm text-white placeholder:text-hc-muted/50 focus:outline-none focus:border-hc-teal-light" />
              </div>
              <div>
                <label className="text-[10px] text-hc-muted uppercase tracking-wider font-semibold mb-1 block">Incoming Staff</label>
                <input value={staffIn} onChange={e => setStaffIn(e.target.value)} placeholder="Name" className="w-full bg-hc-dark border border-hc-border rounded-lg px-3 py-2 text-sm text-white placeholder:text-hc-muted/50 focus:outline-none focus:border-hc-teal-light" />
              </div>
            </div>
          </div>

          {/* Add item */}
          <div className="bg-hc-card border border-hc-border rounded-xl p-4">
            <div className="flex flex-wrap gap-1.5 mb-3">
              {CATEGORIES.map(cat => (
                <button
                  key={cat.id}
                  onClick={() => setNewCategory(cat.id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] border transition-all ${
                    newCategory === cat.id
                      ? 'font-semibold'
                      : 'border-hc-border text-hc-muted hover:text-white'
                  }`}
                  style={newCategory === cat.id ? { color: cat.color, borderColor: `${cat.color}40`, background: `${cat.color}10` } : {}}
                >
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d={cat.icon} /></svg>
                  {cat.label}
                </button>
              ))}
            </div>

            <div className="flex gap-2">
              <textarea
                value={newText}
                onChange={e => setNewText(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); addItem(); } }}
                placeholder="Type handover item... (Enter to add)"
                className="flex-1 bg-hc-dark border border-hc-border rounded-lg px-3 py-2 text-sm text-white placeholder:text-hc-muted/50 focus:outline-none focus:border-hc-teal-light resize-none"
                rows={2}
              />
              <div className="flex flex-col gap-1.5">
                <div className="flex gap-1">
                  {(['none', 'amber', 'red'] as const).map(s => (
                    <button
                      key={s}
                      onClick={() => setNewSeverity(s)}
                      className={`w-6 h-6 rounded-md border transition-all ${
                        newSeverity === s ? 'scale-110' : 'opacity-40 hover:opacity-70'
                      }`}
                      style={{
                        borderColor: s === 'red' ? '#ef4444' : s === 'amber' ? '#f59e0b' : '#334155',
                        background: s === 'red' ? 'rgba(239,68,68,0.2)' : s === 'amber' ? 'rgba(245,158,11,0.2)' : 'rgba(51,65,85,0.2)',
                      }}
                      title={s === 'none' ? 'No flag' : s.charAt(0).toUpperCase() + s.slice(1)}
                    />
                  ))}
                </div>
                <button onClick={addItem} disabled={!newText.trim()} className="px-3 py-2 bg-hc-teal text-white text-xs font-semibold rounded-lg hover:bg-hc-teal-light disabled:opacity-40 transition-all">
                  Add
                </button>
              </div>
            </div>
          </div>

          {/* Items list */}
          {items.length > 0 && (
            <div className="space-y-1.5">
              {items.map(item => {
                const cat = CATEGORIES.find(c => c.id === item.category);
                return (
                  <div
                    key={item.id}
                    className={`bg-hc-card border rounded-xl p-3 flex items-start gap-3 transition-all ${
                      item.severity === 'red' ? 'border-flag-red/25' : item.severity === 'amber' ? 'border-flag-amber/25' : 'border-hc-border'
                    } ${item.resolved ? 'opacity-50' : ''}`}
                  >
                    <button onClick={() => toggleResolved(item.id)} className={`mt-0.5 w-4 h-4 rounded border-2 shrink-0 flex items-center justify-center ${item.resolved ? 'bg-flag-green border-flag-green' : 'border-hc-muted'}`}>
                      {item.resolved && <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>}
                    </button>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="text-[10px] font-semibold" style={{ color: cat?.color }}>{cat?.label}</span>
                        {item.severity !== 'none' && (
                          <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded-full ${
                            item.severity === 'red' ? 'bg-flag-red/15 text-flag-red' : 'bg-flag-amber/15 text-flag-amber'
                          }`}>{item.severity.toUpperCase()}</span>
                        )}
                      </div>
                      <div className={`text-xs text-hc-text ${item.resolved ? 'line-through' : ''}`}>{item.text}</div>
                    </div>
                    <button onClick={() => removeItem(item.id)} className="text-hc-muted hover:text-flag-red shrink-0">
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right — Preview */}
        <div className="lg:col-span-2">
          <div className="sticky top-6">
            <div className="bg-hc-card border border-hc-border rounded-xl overflow-hidden">
              <div className="p-4 border-b border-hc-border flex items-center justify-between">
                <div>
                  <div className="text-xs font-semibold text-white">Handover Preview</div>
                  <div className="text-[10px] text-hc-muted">{items.length} items · {items.filter(i => !i.resolved).length} unresolved</div>
                </div>
                <div className="flex gap-2">
                  <button onClick={copyToClipboard} className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all ${copied ? 'bg-flag-green text-white' : 'bg-hc-teal text-white hover:bg-hc-teal-light'}`}>
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button onClick={saveHandover} disabled={items.length === 0} className="px-3 py-1.5 bg-hc-card border border-hc-border text-xs text-hc-muted rounded-lg hover:text-white disabled:opacity-40">
                    Save
                  </button>
                </div>
              </div>
              <pre className="p-4 text-[11px] text-hc-text font-mono leading-relaxed whitespace-pre-wrap max-h-[500px] overflow-y-auto">
                {items.length > 0 ? generateHandoverText() : 'Add handover items to see preview...'}
              </pre>
            </div>

            {/* History */}
            {history.length > 0 && (
              <div className="mt-3">
                <button onClick={() => setShowHistory(!showHistory)} className="flex items-center gap-2 text-xs text-hc-muted hover:text-white w-full">
                  <svg className={`w-3 h-3 transition-transform ${showHistory ? 'rotate-90' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" /></svg>
                  Recent Handovers ({history.length})
                </button>
                {showHistory && (
                  <div className="mt-2 space-y-1.5 max-h-[200px] overflow-y-auto">
                    {history.slice(0, 10).map(h => (
                      <div key={h.id} className="bg-hc-card border border-hc-border rounded-lg p-2.5 text-[10px]">
                        <div className="flex items-center justify-between">
                          <span className="text-white font-semibold">{h.house}</span>
                          <span className="text-hc-muted">{h.date}</span>
                        </div>
                        <div className="text-hc-muted">{h.shiftFrom} → {h.shiftTo} · {h.items.length} items</div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
